import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { db } from "@/lib/database"
import { getTenantAccess } from "@/lib/tenant-access"

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ tenant: string }> }
) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

    const { tenant: tenantSlug } = await params
    const access = await getTenantAccess(session, tenantSlug)
    if (!access) return NextResponse.json({ error: "Forbidden" }, { status: 403 })

    // 1. Fetch all tenant structures
    const [contentTypesRaw, singleTypesRaw] = await Promise.all([
      db.contentType.findMany({
        where: { OR: [{ tenantId: access.tenantId }, { tenantId: null }] },
        include: { schemaFields: true }
      }),
      db.singleType.findMany({
        where: { tenantId: access.tenantId },
        include: { schemaFields: true }
      })
    ])

    const contentTypes = contentTypesRaw.map(ct => ({ ...ct, fields: ct.schemaFields }))
    const singleTypes = singleTypesRaw.map(st => ({ ...st, fields: st.schemaFields }))

    const baseUrl = process.env.NEXTAUTH_URL || "http://localhost:3000"

    // 2. Build OpenAPI Object
    const spec: any = {
      openapi: "3.0.0",
      info: {
        title: `API Documentation - ${access.tenant.name}`,
        description: `Dynamic API documentation for ${access.tenant.name} workspace generated by SaCMS.`,
        version: "1.0.0",
      },
      servers: [
        {
          url: `${baseUrl}/api/public/${tenantSlug}`,
          description: "Public API Gateway"
        }
      ],
      components: {
        securitySchemes: {
          BearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
            description: "Enter your API Key as Bearer token."
          }
        },
        schemas: {}
      },
      security: [{ BearerAuth: [] }],
      paths: {}
    }

    // 3. Map Content Types to Paths & Schemas
    contentTypes.forEach(ct => {
      const schemaName = ct.slug.charAt(0).toUpperCase() + ct.slug.slice(1)
      
      // Define Schema
      spec.components.schemas[schemaName] = {
        type: "object",
        properties: {
          id: { type: "string" },
          status: { type: "string", enum: ["DRAFT", "PUBLISHED", "ARCHIVED"] },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
          data: {
            type: "object",
            properties: ct.fields.reduce((acc: any, f) => {
              let type = "string"
              if (f.type === "number") type = "number"
              if (f.type === "boolean") type = "boolean"
              if (f.type === "json") type = "object"
              
              acc[f.slug] = { 
                type, 
                description: f.name,
                ...(f.required ? { nullable: false } : { nullable: true })
              }
              return acc
            }, {})
          }
        }
      }

      // Define Paths
      spec.paths[`/content/${ct.slug}`] = {
        get: {
          summary: `List all ${ct.name} entries`,
          tags: ["Collection Types"],
          responses: {
            200: {
              description: "Array of entries",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      entries: { type: "array", items: { $ref: `#/components/schemas/${schemaName}` } }
                    }
                  }
                }
              }
            }
          }
        },
        post: {
          summary: `Create a new ${ct.name}`,
          tags: ["Collection Types"],
          requestBody: {
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    data: { $ref: `#/components/schemas/${schemaName}` }
                  }
                }
              }
            }
          },
          responses: { 201: { description: "Created" } }
        }
      }

      spec.paths[`/content/${ct.slug}/{id}`] = {
        get: {
          summary: `Get a specific ${ct.name} by ID`,
          tags: ["Collection Types"],
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: { 200: { description: "Success" } }
        },
        patch: {
          summary: `Update a ${ct.name} entry`,
          tags: ["Collection Types"],
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: { 200: { description: "Updated" } }
        },
        delete: {
          summary: `Delete a ${ct.name} entry`,
          tags: ["Collection Types"],
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: { 204: { description: "Deleted" } }
        }
      }
    })

    // 4. Map Single Types
    singleTypes.forEach(st => {
      spec.paths[`/single/${st.slug}`] = {
        get: {
          summary: `Get ${st.name} data`,
          tags: ["Single Types"],
          responses: { 200: { description: "Success" } }
        }
      }
    })

    return NextResponse.json(spec)
  } catch (error) {
    console.error("OpenAPI Generator Error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
