export const aiTemplates = {
  schema: [
    { label: "Blog Post", prompt: "Rancang skema Blog Post yang komprehensif untuk kebutuhan publikasi artikel, mencakup detail editorial, media visual, serta relasi kategori dan penulis." },
    { label: "CMS User/Staff", prompt: "Buatkan skema profil Pengguna/Staff CMS yang mencakup data identitas diri, kredensial, posisi jabatan, dan status keanggotaan untuk manajemen akses." },
    { label: "Berita", prompt: "Desain skema publikasi Berita jurnalistik yang mencakup elemen artikel utama, ringkasan, media penunjang, serta metadata penerbitan." },
    { label: "Pengumuman", prompt: "Buat skema papan Pengumuman Resmi yang mendukung penyampaian informasi, lampiran dokumen pendukung, dan rentang waktu validitas publikasi." },
    { label: "Dokumen Publikasi", prompt: "Rancang skema arsip Dokumen Publikasi untuk mengelola berkas laporan atau panduan, lengkap dengan detail penerbit dan kategorisasinya." },
    { label: "Agenda Acara", prompt: "Buatkan skema sistem manajemen Agenda Acara yang mencakup informasi jadwal, lokasi, penyelenggara, serta visual pendukung kegiatan." },
    { label: "Produk Katalog", prompt: "Desain skema Katalog Produk e-commerce yang komprehensif, meliputi spesifikasi detail, manajemen harga, stok, dan variasi galeri visual." },
    { label: "Properti/Rumah", prompt: "Rancang skema Listing Properti yang memuat informasi detail fisik bangunan, fasilitas, metrik harga, dan visualisasi galeri yang lengkap." },
    { label: "Kursus/E-learning", prompt: "Buat skema modul pembelajaran Kursus (E-learning) yang mencakup struktur materi, profil instruktur, serta detail biaya dan tingkat kesulitan." },
    { label: "Portofolio", prompt: "Desain skema pameran Portofolio proyek profesional yang menyoroti detail klien, teknologi yang digunakan, serta dokumentasi galeri hasil karya." },
    { label: "Testimoni", prompt: "Buatkan skema ulasan Testimoni Pelanggan untuk memvalidasi kepuasan layanan, mencakup identitas reviewer, skor rating, dan status moderasi." },
    { label: "Tim Kami", prompt: "Rancang skema profil Anggota Tim untuk halaman 'Tentang Kami', menampilkan hierarki jabatan, bio profesional, dan tautan kontak." },
    { label: "Partner/Klien", prompt: "Buat skema direktori Partner atau Klien bisnis, mencakup identitas brand, tingkatan kemitraan, dan media logo representatif." },
    { label: "Galeri Foto", prompt: "Desain skema Album Galeri interaktif untuk mengelola koleksi visual dari suatu acara, lengkap dengan deskripsi dan metadata waktu." },
    { label: "FAQ", prompt: "Buatkan skema pusat bantuan Tanya Jawab (FAQ) yang terstruktur berdasarkan kategori permasalahan untuk memudahkan pengguna." },
    { label: "Lowongan Kerja", prompt: "Rancang skema portal Lowongan Kerja (Karir) yang mencakup detail spesifikasi peran, persyaratan kandidat, dan parameter penawaran posisi." },
    { label: "Newsletter", prompt: "Buat skema manajemen pelanggan Subscriber Newsletter untuk melacak partisipasi pengguna dan status berlangganan email." }
  ],
  "single-type": [
    { label: "Landing Page", prompt: "Rancang struktur halaman Landing Page utama yang mencakup elemen hero, section fitur, dan pengaturan konversi (Call to Action)." },
    { label: "Tentang Kami", prompt: "Buatkan skema halaman Tentang Kami (About Us) yang menceritakan visi misi, jejak sejarah perusahaan, dan pencapaian bisnis." },
    { label: "Hubungi Kami", prompt: "Desain skema halaman Hubungi Kami yang mencakup semua saluran komunikasi resmi, alamat operasional, dan lokasi koordinat." },
    { label: "Kebijakan Privasi", prompt: "Buat skema halaman Kebijakan Privasi (Privacy Policy) untuk menampilkan dokumen legalitas dan aturan kepatuhan secara terpusat." },
    { label: "Navigasi/Menu", prompt: "Rancang skema konfigurasi Navigasi/Menu utama website yang mengatur struktur tautan hierarkis dan pengaturan header visual." },
    { label: "Pengaturan SEO", prompt: "Buatkan skema Pengaturan Global SEO untuk mengontrol metadata, performa pencarian, dan integrasi webmaster pada seluruh situs." },
    { label: "Pengaturan Global", prompt: "Desain skema Pengaturan Sistem Global untuk mengelola identitas utama website, mode pemeliharaan, dan konfigurasi dasar lainnya." },
    { label: "Footer Config", prompt: "Rancang skema konfigurasi Footer website yang menampung informasi hak cipta, tautan legal, dan direktori kontak navigasi bawah." }
  ],
  component: [
    { label: "Pricing Card", prompt: "Buat komponen Pricing Card untuk menampilkan paket berlangganan dengan detail harga, daftar fitur unggulan, dan aksi konversi." },
    { label: "Hero Banner", prompt: "Desain komponen Hero Banner dengan lapisan visual yang menarik, teks utama, dan elemen pemanggil aksi (Call to Action)." },
    { label: "Feature Item", prompt: "Rancang komponen Feature Item untuk menyoroti keunggulan spesifik menggunakan ikon representatif dan deskripsi singkat." },
    { label: "Accordion/FAQ", prompt: "Buat komponen Accordion untuk menyajikan informasi tersembunyi seperti FAQ yang dapat dibuka-tutup secara interaktif." },
    { label: "Stat Counter", prompt: "Desain komponen Statistik (Stat Counter) untuk menampilkan pencapaian angka yang dinamis dengan label metrik yang jelas." },
    { label: "Social Link", prompt: "Buatkan komponen Social Media Link untuk memetakan tautan profil media sosial beserta status ketersediaannya." },
    { label: "Logo Grid", prompt: "Rancang komponen Logo Grid (Cloud) untuk menampilkan deretan logo mitra atau klien dalam format galeri yang rapi." },
    { label: "Testimonial Card", prompt: "Buat komponen Testimonial Card yang elegan untuk menampilkan ulasan positif pengguna beserta identitas profesional mereka." },
    { label: "CTA Block", prompt: "Desain komponen Call to Action (CTA) Block yang dirancang khusus untuk mendorong pengguna melakukan aksi spesifik." },
    { label: "Steps/Process", prompt: "Rancang komponen Langkah-langkah (Process Steps) untuk menjelaskan alur kerja secara berurutan dan terstruktur." },
    { label: "Team Member", prompt: "Buat komponen profil Team Member untuk memvisualisasikan anggota staf dengan foto, peranan, dan koneksi profesional mereka." },
    { label: "Gallery Item", prompt: "Desain komponen Gallery Item tunggal yang difokuskan pada presentasi visual media dengan konteks deskriptif." },
    { label: "Tab Content", prompt: "Buatkan komponen Tab Content untuk memisahkan beberapa informasi dalam navigasi tabuler yang interaktif dan hemat ruang." },
    { label: "Video Block", prompt: "Rancang komponen Video Section untuk menyematkan tayangan multimedia dengan dukungan thumbnail visual dan meta durasi." },
    { label: "Contact Info", prompt: "Buat komponen Contact Info yang serbaguna untuk merangkum detail satu jalur komunikasi secara ikonik." },
    { label: "Comparison Row", prompt: "Desain komponen Comparison Row untuk membedah perbandingan kapabilitas atau fitur antar produk secara detail." },
    { label: "Banner Info", prompt: "Buatkan komponen Banner Notifikasi (Info) yang ringkas untuk menyampaikan pengumuman singkat dengan opsi aksi cepat." },
    { label: "Card Versatile", prompt: "Rancang komponen Kartu Serbaguna (Versatile Card) yang fleksibel untuk memuat kombinasi teks, media, dan tautan dalam berbagai orientasi." },
    { label: "Progress Bar", prompt: "Buat komponen Progress Bar untuk menvisualisasikan metrik pencapaian atau persentase keterampilan secara grafis." },
    { label: "Timeline Item", prompt: "Desain komponen Timeline Item untuk menceritakan riwayat peristiwa historis atau jejak pencapaian secara kronologis." },
    { label: "Breadcrumb Item", prompt: "Buatkan komponen Navigasi Breadcrumb untuk menunjukkan jejak hierarki halaman agar mempermudah penjelajahan pengguna." },
    { label: "Link Column", prompt: "Rancang komponen Kolom Tautan (Link Column) khusus untuk mengelompokkan daftar menu navigasi pada area struktur bawah (footer)." }
  ]
}
