services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_SECRET=a_very_long_random_string_for_development_purposes
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - SENTRY_IGNORE_API_RESOLUTION_ERROR=1
      - SENTRY_DISABLE_SERVER_SIDE_SOURCE_MAPS=1

