/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 * This file was generated by scripts/generate-sdk-types.ts
 */

export interface BaseEntry {
  id: string
  locale: string
  status: string
  publishedAt: string | null
  createdAt: string
  updatedAt: string
}

/** Blog (No description) */
export interface Blog extends BaseEntry {
  judul_berita?: string
}

/** Homepage (Single Type: No description) */
export interface Homepage extends BaseEntry {
  judul: string
}

export interface ContentFlowRegistry {
  "blog": Blog
  "homepage": Homepage
}
