
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  image: 'image',
  role: 'role',
  emailVerified: 'emailVerified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  plan: 'plan'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.TenantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  logo: 'logo',
  plan: 'plan',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  brandLogo: 'brandLogo',
  brandName: 'brandName',
  customDomain: 'customDomain',
  customDomainStatus: 'customDomainStatus',
  customDomainVerifiedAt: 'customDomainVerifiedAt',
  customEmailSender: 'customEmailSender',
  databaseUrl: 'databaseUrl',
  faviconUrl: 'faviconUrl',
  primaryColor: 'primaryColor',
  storageConfig: 'storageConfig'
};

exports.Prisma.TenantMemberScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  role: 'role',
  joinedAt: 'joinedAt',
  customPermissions: 'customPermissions'
};

exports.Prisma.CustomPlanOverrideScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tenantId: 'tenantId',
  maxWorkspaces: 'maxWorkspaces',
  maxContentTypes: 'maxContentTypes',
  maxContentEntries: 'maxContentEntries',
  maxTeamMembers: 'maxTeamMembers',
  maxStorage: 'maxStorage',
  maxLocales: 'maxLocales',
  maxApiCalls: 'maxApiCalls',
  note: 'note',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContentTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tenantId: 'tenantId',
  docxTemplateUrl: 'docxTemplateUrl'
};

exports.Prisma.SchemaFieldScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  type: 'type',
  required: 'required',
  unique: 'unique',
  order: 'order',
  jsonPath: 'jsonPath',
  localizable: 'localizable',
  relationSlug: 'relationSlug',
  options: 'options',
  contentTypeId: 'contentTypeId',
  singleTypeId: 'singleTypeId',
  componentId: 'componentId'
};

exports.Prisma.TenantContentTypeAssignmentScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  contentTypeId: 'contentTypeId',
  enabled: 'enabled',
  createdAt: 'createdAt'
};

exports.Prisma.ContentEntryScalarFieldEnum = {
  id: 'id',
  contentTypeId: 'contentTypeId',
  tenantId: 'tenantId',
  publishedAt: 'publishedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  archivedAt: 'archivedAt',
  locale: 'locale',
  reviewComment: 'reviewComment',
  scheduledAt: 'scheduledAt',
  status: 'status',
  data: 'data',
  documentId: 'documentId'
};

exports.Prisma.ContentVersionScalarFieldEnum = {
  id: 'id',
  contentEntryId: 'contentEntryId',
  version: 'version',
  publishedAt: 'publishedAt',
  changeType: 'changeType',
  changedBy: 'changedBy',
  changeSummary: 'changeSummary',
  createdAt: 'createdAt',
  data: 'data'
};

exports.Prisma.ContentReviewAssignmentScalarFieldEnum = {
  id: 'id',
  contentEntryId: 'contentEntryId',
  reviewerId: 'reviewerId',
  reviewerName: 'reviewerName',
  order: 'order',
  status: 'status',
  comment: 'comment',
  reviewedAt: 'reviewedAt',
  assignedBy: 'assignedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SingleTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isPublished: 'isPublished',
  tenantId: 'tenantId'
};

exports.Prisma.SingleTypeFieldScalarFieldEnum = {
  id: 'id',
  singleTypeId: 'singleTypeId',
  name: 'name',
  slug: 'slug',
  type: 'type',
  required: 'required',
  order: 'order',
  jsonPath: 'jsonPath',
  localizable: 'localizable',
  relationSlug: 'relationSlug',
  unique: 'unique',
  options: 'options'
};

exports.Prisma.TenantSingleTypeAssignmentScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  singleTypeId: 'singleTypeId',
  enabled: 'enabled',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  locale: 'locale',
  data: 'data'
};

exports.Prisma.ComponentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tenantId: 'tenantId'
};

exports.Prisma.ComponentFieldScalarFieldEnum = {
  id: 'id',
  componentId: 'componentId',
  name: 'name',
  slug: 'slug',
  type: 'type',
  required: 'required',
  order: 'order',
  jsonPath: 'jsonPath',
  localizable: 'localizable',
  relationSlug: 'relationSlug',
  unique: 'unique',
  options: 'options'
};

exports.Prisma.TenantComponentAssignmentScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  componentId: 'componentId',
  enabled: 'enabled',
  createdAt: 'createdAt'
};

exports.Prisma.ApiKeyScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  key: 'key',
  lastUsed: 'lastUsed',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  permissions: 'permissions'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tenantId: 'tenantId',
  plan: 'plan',
  status: 'status',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  midtransCustomerId: 'midtransCustomerId',
  midtransSubscriptionId: 'midtransSubscriptionId'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  midtransInvoiceId: 'midtransInvoiceId'
};

exports.Prisma.PaymentTransactionScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  invoiceId: 'invoiceId',
  orderId: 'orderId',
  paymentType: 'paymentType',
  paymentMethod: 'paymentMethod',
  amount: 'amount',
  status: 'status',
  transactionId: 'transactionId',
  transactionTime: 'transactionTime',
  fraudStatus: 'fraudStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  rawResponse: 'rawResponse'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  data: 'data'
};

exports.Prisma.SettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  tenantId: 'tenantId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemMetricScalarFieldEnum = {
  id: 'id',
  type: 'type',
  value: 'value',
  timestamp: 'timestamp',
  metadata: 'metadata'
};

exports.Prisma.ApiRequestScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  endpoint: 'endpoint',
  method: 'method',
  statusCode: 'statusCode',
  duration: 'duration',
  apiKeyId: 'apiKeyId',
  createdAt: 'createdAt'
};

exports.Prisma.MediaFolderScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  path: 'path',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  folderId: 'folderId',
  name: 'name',
  originalName: 'originalName',
  mimeType: 'mimeType',
  size: 'size',
  url: 'url',
  thumbnailUrl: 'thumbnailUrl',
  alt: 'alt',
  caption: 'caption',
  width: 'width',
  height: 'height',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  mediumUrl: 'mediumUrl',
  storageKey: 'storageKey',
  metadata: 'metadata',
  isPrivate: 'isPrivate'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  description: 'description',
  category: 'category',
  createdAt: 'createdAt'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionId: 'permissionId',
  granted: 'granted',
  tenantId: 'tenantId'
};

exports.Prisma.TenantRoleScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApiTokenScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  token: 'token',
  type: 'type',
  lastUsedAt: 'lastUsedAt',
  expiresAt: 'expiresAt',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  permissions: 'permissions'
};

exports.Prisma.WebhookScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  url: 'url',
  secret: 'secret',
  enabled: 'enabled',
  lastTriggeredAt: 'lastTriggeredAt',
  failureCount: 'failureCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  hookType: 'hookType',
  events: 'events',
  headers: 'headers'
};

exports.Prisma.WebhookLogScalarFieldEnum = {
  id: 'id',
  webhookId: 'webhookId',
  event: 'event',
  statusCode: 'statusCode',
  success: 'success',
  duration: 'duration',
  error: 'error',
  createdAt: 'createdAt',
  payload: 'payload',
  response: 'response'
};

exports.Prisma.WebhookDeadLetterScalarFieldEnum = {
  id: 'id',
  webhookId: 'webhookId',
  event: 'event',
  payload: 'payload',
  lastError: 'lastError',
  attempts: 'attempts',
  maxAttempts: 'maxAttempts',
  nextRetryAt: 'nextRetryAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TenantLocaleScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  locale: 'locale',
  name: 'name',
  isDefault: 'isDefault',
  isEnabled: 'isEnabled'
};

exports.Prisma.EnterpriseLicenseScalarFieldEnum = {
  id: 'id',
  licenseKey: 'licenseKey',
  customerName: 'customerName',
  customerEmail: 'customerEmail',
  customerPhone: 'customerPhone',
  organization: 'organization',
  type: 'type',
  features: 'features',
  maxInstances: 'maxInstances',
  issuedAt: 'issuedAt',
  expiresAt: 'expiresAt',
  lastValidatedAt: 'lastValidatedAt',
  validatedCount: 'validatedCount',
  status: 'status',
  metadata: 'metadata',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LicenseCacheScalarFieldEnum = {
  id: 'id',
  licenseKey: 'licenseKey',
  customerName: 'customerName',
  customerEmail: 'customerEmail',
  type: 'type',
  features: 'features',
  issuedAt: 'issuedAt',
  expiresAt: 'expiresAt',
  lastValidatedAt: 'lastValidatedAt',
  status: 'status',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.ContentStatus = exports.$Enums.ContentStatus = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  SCHEDULED: 'SCHEDULED',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Tenant: 'Tenant',
  TenantMember: 'TenantMember',
  CustomPlanOverride: 'CustomPlanOverride',
  ContentType: 'ContentType',
  SchemaField: 'SchemaField',
  TenantContentTypeAssignment: 'TenantContentTypeAssignment',
  ContentEntry: 'ContentEntry',
  ContentVersion: 'ContentVersion',
  ContentReviewAssignment: 'ContentReviewAssignment',
  SingleType: 'SingleType',
  SingleTypeField: 'SingleTypeField',
  TenantSingleTypeAssignment: 'TenantSingleTypeAssignment',
  Component: 'Component',
  ComponentField: 'ComponentField',
  TenantComponentAssignment: 'TenantComponentAssignment',
  ApiKey: 'ApiKey',
  Subscription: 'Subscription',
  Invoice: 'Invoice',
  PaymentTransaction: 'PaymentTransaction',
  AuditLog: 'AuditLog',
  Setting: 'Setting',
  SystemMetric: 'SystemMetric',
  ApiRequest: 'ApiRequest',
  MediaFolder: 'MediaFolder',
  Media: 'Media',
  Permission: 'Permission',
  RolePermission: 'RolePermission',
  TenantRole: 'TenantRole',
  ApiToken: 'ApiToken',
  Webhook: 'Webhook',
  WebhookLog: 'WebhookLog',
  WebhookDeadLetter: 'WebhookDeadLetter',
  TenantLocale: 'TenantLocale',
  EnterpriseLicense: 'EnterpriseLicense',
  LicenseCache: 'LicenseCache'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
