import { db } from "../src/lib/database.ts"
import fs from "fs"
import path from "path"

/**
 * Script to generate TypeScript interfaces for the SDK based on ContentTypes in the database.
 * This provides end-to-end type safety for API consumers.
 */

async function generate() {
  console.log("Generating SDK types...")

  const contentTypes = await db.contentType.findMany({
    include: {
      fields: { orderBy: { order: "asc" } },
    },
  })

  const singleTypes = await db.singleType.findMany({
    include: {
      fields: { orderBy: { order: "asc" } },
    },
  })

  let output = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 * This file was generated by scripts/generate-sdk-types.ts
 */

export interface BaseEntry {
  id: string
  locale: string
  status: string
  publishedAt: string | null
  createdAt: string
  updatedAt: string
}

`

  // Generate Collection Types
  for (const ct of contentTypes) {
    const interfaceName = toPascalCase(ct.slug)
    output += `/** ${ct.name} (${ct.description || "No description"}) */\n`
    output += `export interface ${interfaceName} extends BaseEntry {\n`
    
    for (const field of ct.fields) {
      const tsType = mapFieldToTS(field.type, field.relationSlug)
      const optional = field.required ? "" : "?"
      output += `  ${field.slug}${optional}: ${tsType}\n`
    }
    
    output += `}\n\n`
  }

  // Generate Single Types
  for (const st of singleTypes) {
    const interfaceName = toPascalCase(st.slug)
    output += `/** ${st.name} (Single Type: ${st.description || "No description"}) */\n`
    output += `export interface ${interfaceName} extends BaseEntry {\n`
    
    for (const field of st.fields) {
      const tsType = mapFieldToTS(field.type, field.relationSlug)
      const optional = field.required ? "" : "?"
      output += `  ${field.slug}${optional}: ${tsType}\n`
    }
    
    output += `}\n\n`
  }

  // Add Registry for dynamic lookup
  output += `export interface ContentFlowRegistry {\n`
  for (const ct of contentTypes) {
    output += `  "${ct.slug}": ${toPascalCase(ct.slug)}\n`
  }
  for (const st of singleTypes) {
    output += `  "${st.slug}": ${toPascalCase(st.slug)}\n`
  }
  output += `}\n`

  const outputPath = path.join(process.cwd(), "mini-services/sdk/src/generated-types.ts")
  fs.writeFileSync(outputPath, output)
  
  console.log(`Successfully generated ${contentTypes.length + singleTypes.length} types to ${outputPath}`)
}

function toPascalCase(str: string) {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())
    .replace(/^(.)/, (m, chr) => chr.toUpperCase())
}

function mapFieldToTS(type: string, relationSlug?: string | null): string {
  switch (type) {
    case "integer":
    case "decimal":
    case "biginteger":
    case "float":
      return "number"
    case "boolean":
      return "boolean"
    case "json":
      return "any"
    case "media":
      return "{ url: string, name: string, mimeType: string, size: number }"
    case "mediaMultiple":
      return "Array<{ url: string, name: string, mimeType: string, size: number }>"
    case "relation":
      return relationSlug ? `${toPascalCase(relationSlug)} | string` : "any"
    default:
      return "string"
  }
}

generate()
  .catch(console.error)
  .finally(() => db.$disconnect())
