/**
 * Multi-Page Dynamic Next.js Website Code Generator
 *
 * Scaffolds complete Next.js 16 App Router websites connected to SaCMS Content API
 * with typed SDKs, multi-page routing, UI components, and responsive design.
 */

import { SchemaPlan } from "@/lib/ai/schema-engine"

export interface WebsiteGenerationParams {
  tenantId: string
  tenantSlug: string
  siteName: string
  siteSlug: string
  description?: string
  plan: SchemaPlan
}

export function generateFullWebsiteProject({
  tenantId,
  tenantSlug,
  siteName,
  siteSlug,
  description,
  plan,
}: WebsiteGenerationParams): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = []
  const contentTypes = plan.contentTypes || []
  const singleTypes = plan.singleTypes || []

  // ── 1. types/content.d.ts ──────────────────────────────────────────────────
  const typeDefinitions = contentTypes.map((ct) => {
    const fieldsTs = ct.fields
      .map((f) => {
        const tsType = f.type === "number" ? "number" : f.type === "boolean" ? "boolean" : "string"
        return `    ${f.slug}${f.required ? "" : "?"}: ${tsType};`
      })
      .join("\n")

    return `export interface ${ct.name} {
  id: string;
  createdAt: string;
  updatedAt: string;
  data: {
${fieldsTs}
  };
}`
  }).join("\n\n")

  files.push({
    path: "types/content.d.ts",
    content: `/**
 * TypeScript Type Definitions for SaCMS Workspace: ${tenantSlug}
 * Auto-generated by SaCMS AI Website Builder
 */

${typeDefinitions}
`,
  })

  // ── 2. lib/sacms.ts ────────────────────────────────────────────────────────
  files.push({
    path: "lib/sacms.ts",
    content: `/**
 * SaCMS Content API Client
 * Workspace: ${tenantSlug} (${tenantId})
 */

const SACMS_HOST = process.env.NEXT_PUBLIC_SACMS_URL || "http://localhost:3000";
const TENANT_ID = "${tenantId}";

export async function getCollection<T = any>(
  contentTypeSlug: string,
  params: Record<string, string> = {}
): Promise<T[]> {
  try {
    const query = new URLSearchParams(params).toString();
    const url = \`\${SACMS_HOST}/api/public/\${TENANT_ID}/content/\${contentTypeSlug}\${query ? '?' + query : ''}\`;
    const res = await fetch(url, { next: { revalidate: 60 } });
    if (!res.ok) return [];
    const json = await res.json();
    return json.data || json.entries || [];
  } catch (e) {
    console.error(\`[SaCMS SDK] Failed to fetch collection '\${contentTypeSlug}':\`, e);
    return [];
  }
}

export async function getEntry<T = any>(
  contentTypeSlug: string,
  idOrSlug: string
): Promise<T | null> {
  try {
    const url = \`\${SACMS_HOST}/api/public/\${TENANT_ID}/content/\${contentTypeSlug}/\${idOrSlug}\`;
    const res = await fetch(url, { next: { revalidate: 60 } });
    if (!res.ok) return null;
    const json = await res.json();
    return json.data || json.entry || null;
  } catch (e) {
    console.error(\`[SaCMS SDK] Failed to fetch entry '\${idOrSlug}':\`, e);
    return null;
  }
}

export async function getSingleType<T = any>(singleTypeSlug: string): Promise<T | null> {
  try {
    const url = \`\${SACMS_HOST}/api/public/\${TENANT_ID}/single/\${singleTypeSlug}\`;
    const res = await fetch(url, { next: { revalidate: 60 } });
    if (!res.ok) return null;
    const json = await res.json();
    return json.data || null;
  } catch (e) {
    console.error(\`[SaCMS SDK] Failed to fetch single type '\${singleTypeSlug}':\`, e);
    return null;
  }
}`,
  })

  // ── 3. components/Navbar.tsx ───────────────────────────────────────────────
  const navLinks = contentTypes.map((ct) => ({
    label: ct.name,
    href: `/${ct.slug}`,
  }))

  files.push({
    path: "components/Navbar.tsx",
    content: `import Link from "next/link";
import { Sparkles, Globe, ArrowRight } from "lucide-react";

export function Navbar() {
  const links = ${JSON.stringify(navLinks, null, 2)};

  return (
    <header className="border-b border-slate-800 bg-slate-950/80 backdrop-blur sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2.5 font-extrabold text-lg text-white hover:text-indigo-400 transition-colors">
          <div className="h-8 w-8 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-xs">
            <Sparkles className="h-4 w-4" />
          </div>
          <span>${siteName}</span>
        </Link>

        <nav className="hidden md:flex items-center gap-6 text-xs font-semibold text-slate-300">
          <Link href="/" className="hover:text-indigo-400 transition-colors">Beranda</Link>
          {links.map((l) => (
            <Link key={l.href} href={l.href} className="hover:text-indigo-400 transition-colors">
              {l.label}
            </Link>
          ))}
          <Link href="/contact" className="hover:text-indigo-400 transition-colors">Kontak</Link>
        </nav>

        <div className="flex items-center gap-3">
          <Link
            href="/contact"
            className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-xs transition-colors"
          >
            Hubungi Kami
          </Link>
        </div>
      </div>
    </header>
  );
}`,
  })

  // ── 4. components/Footer.tsx ───────────────────────────────────────────────
  files.push({
    path: "components/Footer.tsx",
    content: `import Link from "next/link";
import { Globe, Sparkles } from "lucide-react";

export function Footer() {
  return (
    <footer className="border-t border-slate-800 bg-slate-950 text-slate-400 py-12 px-6">
      <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-6 text-xs">
        <div className="flex items-center gap-2 text-slate-200 font-bold">
          <Globe className="h-4 w-4 text-indigo-400" />
          <span>${siteName}</span>
        </div>
        <p className="text-slate-500 text-center sm:text-left">
          &copy; {new Date().getFullYear()} ${siteName}. All rights reserved. Powered by SaCMS Headless CMS.
        </p>
        <div className="flex items-center gap-4 text-slate-400">
          <Link href="/" className="hover:text-white transition-colors">Beranda</Link>
          <Link href="/contact" className="hover:text-white transition-colors">Kontak</Link>
        </div>
      </div>
    </footer>
  );
}`,
  })

  // ── 5. app/layout.tsx ──────────────────────────────────────────────────────
  files.push({
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "${siteName} — Powered by SaCMS",
  description: "${description || `Modern dynamic website for ${siteName}`}",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className="scroll-smooth">
      <body className="antialiased min-h-screen bg-slate-950 text-slate-50 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
        <Navbar />
        <div className="flex-1 flex flex-col">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}`,
  })

  // ── 6. app/page.tsx (Landing Homepage) ─────────────────────────────────────
  const firstCt = contentTypes[0]
  files.push({
    path: "app/page.tsx",
    content: `import { getCollection } from "@/lib/sacms";
import Link from "next/link";
import { Sparkles, ArrowRight, Layers, ShieldCheck, Zap, Star } from "lucide-react";

export default async function HomePage() {
  const featuredItems = await getCollection("${firstCt?.slug || 'items'}");

  return (
    <div className="flex flex-col space-y-20 pb-20">
      {/* Hero Section */}
      <section className="relative py-24 px-6 text-center max-w-5xl mx-auto space-y-8">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 text-xs font-semibold text-indigo-400 shadow-xs">
          <Sparkles className="h-3.5 w-3.5" />
          Selamat Datang di ${siteName}
        </div>

        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white leading-tight">
          Solusi Digital Modern Terintegrasi SaCMS
        </h1>

        <p className="text-slate-400 text-base md:text-lg max-w-2xl mx-auto leading-relaxed">
          ${description || "Platform informasi dan layanan terpercaya dengan pembaruan konten dinamis langsung dari sistem CMS."}
        </p>

        <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
          ${firstCt ? `<Link href="/${firstCt.slug}" className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-xs transition-colors flex items-center gap-2">
            Lihat ${firstCt.name} <ArrowRight className="h-3.5 w-3.5" />
          </Link>` : ""}
          <Link href="/contact" className="px-5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-200 font-bold text-xs transition-colors">
            Hubungi Kami
          </Link>
        </div>
      </section>

      {/* Featured Collection Section */}
      ${firstCt ? `
      <section className="max-w-7xl mx-auto px-6 space-y-8 w-full">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-slate-800 pb-4">
          <div className="space-y-1">
            <h2 className="text-2xl md:text-3xl font-bold text-white">${firstCt.name} Unggulan</h2>
            <p className="text-xs text-slate-400">Data live dari koleksi SaCMS '${firstCt.slug}'</p>
          </div>
          <Link href="/${firstCt.slug}" className="text-xs font-bold text-indigo-400 hover:text-indigo-300 flex items-center gap-1">
            Lihat Semua &rarr;
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {featuredItems.slice(0, 3).map((item: any, i: number) => {
            const data = item.data || item;
            const title = data.title || data.name || "Item Unggulan";
            const desc = data.description || data.excerpt || data.features || "Deskripsi konten dinamis.";
            const price = data.price ? \`Rp \${Number(data.price).toLocaleString("id-ID")}\` : null;

            return (
              <div key={i} className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4 hover:border-indigo-500/40 transition-all flex flex-col justify-between group">
                <div className="space-y-3">
                  <div className="h-44 rounded-xl bg-slate-800 flex items-center justify-center text-slate-500 text-xs font-medium border border-slate-700/60">
                    [Foto: \${title}]
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-bold text-lg text-white group-hover:text-indigo-400 transition-colors">\${title}</h3>
                    {price && <p className="text-indigo-400 font-extrabold text-sm">\${price}</p>}
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed line-clamp-3">\${desc}</p>
                </div>
                <Link
                  href={\`/${firstCt.slug}/\${item.id || i}\`}
                  className="w-full py-2 rounded-xl bg-slate-800 hover:bg-indigo-600 text-xs font-bold text-white text-center transition-colors block mt-2"
                >
                  Detail Lengkap
                </Link>
              </div>
            );
          })}
        </div>
      </section>
      ` : ""}
    </div>
  );
}`,
  })

  // ── 7. Generate Listing & Detail Pages for each Content Type ────────────────
  for (const ct of contentTypes) {
    // Listing page: app/[collection]/page.tsx
    files.push({
      path: `app/${ct.slug}/page.tsx`,
      content: `import { getCollection } from "@/lib/sacms";
import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";

export default async function ${ct.name}ListingPage() {
  const items = await getCollection("${ct.slug}");

  return (
    <div className="max-w-7xl mx-auto px-6 py-12 space-y-8 w-full">
      <div className="space-y-2">
        <div className="inline-flex items-center gap-1.5 text-xs text-indigo-400 font-bold">
          <Sparkles className="h-3.5 w-3.5" />
          Katalog ${ct.name}
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-white">Daftar ${ct.name}</h1>
        <p className="text-xs text-slate-400">${ct.description || `Semua data ${ct.name} yang tersimpan di SaCMS`}</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
        {items.map((item: any, i: number) => {
          const data = item.data || item;
          const title = data.title || data.name || \`${ct.name} #\${i + 1}\`;
          const desc = data.description || data.excerpt || data.features || "Deskripsi lengkap entri konten.";
          const price = data.price ? \`Rp \${Number(data.price).toLocaleString("id-ID")}\` : null;

          return (
            <div key={i} className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4 hover:border-indigo-500/40 transition-all flex flex-col justify-between">
              <div className="space-y-3">
                <div className="h-44 rounded-xl bg-slate-800 flex items-center justify-center text-slate-500 text-xs border border-slate-700/60">
                  [Gambar: \${title}]
                </div>
                <div className="space-y-1">
                  <h3 className="font-bold text-base text-white">\${title}</h3>
                  {price && <p className="text-indigo-400 font-bold text-sm">\${price}</p>}
                </div>
                <p className="text-xs text-slate-400 line-clamp-3 leading-relaxed">\${desc}</p>
              </div>
              <Link
                href={\`/${ct.slug}/\${item.id || i}\`}
                className="w-full py-2 rounded-xl bg-slate-800 hover:bg-indigo-600 text-xs font-bold text-white text-center transition-colors block"
              >
                Lihat Rincian
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
}`,
    })

    // Detail page: app/[collection]/[slug]/page.tsx
    files.push({
      path: `app/${ct.slug}/[slug]/page.tsx`,
      content: `import { getEntry, getCollection } from "@/lib/sacms";
import Link from "next/link";
import { ArrowLeft, Calendar, ShieldCheck } from "lucide-react";

export default async function ${ct.name}DetailPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const item = await getEntry("${ct.slug}", slug);
  const data = item?.data || item || {};
  const title = data.title || data.name || \`Detail ${ct.name}\`;

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-8 w-full">
      <Link href="/${ct.slug}" className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors">
        <ArrowLeft className="h-3.5 w-3.5" /> Kembali ke Katalog ${ct.name}
      </Link>

      <div className="space-y-4">
        <h1 className="text-3xl md:text-5xl font-extrabold text-white">\${title}</h1>
        {data.price && (
          <p className="text-2xl font-bold text-indigo-400">
            Rp {Number(data.price).toLocaleString("id-ID")}
          </p>
        )}
      </div>

      <div className="h-64 md:h-96 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center text-slate-500 text-sm">
        [Media & Galeri: \${title}]
      </div>

      <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-4 leading-relaxed text-sm text-slate-300">
        <h3 className="font-bold text-white text-base">Deskripsi & Informasi Lengkap</h3>
        <p>{data.description || data.content || data.features || "Informasi detail entri konten yang terhubung ke SaCMS."}</p>
      </div>
    </div>
  );
}`,
    })
  }

  // ── 8. app/contact/page.tsx ────────────────────────────────────────────────
  files.push({
    path: "app/contact/page.tsx",
    content: `import { Mail, Phone, MapPin, Send } from "lucide-react";

export default function ContactPage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-16 space-y-12 w-full">
      <div className="text-center space-y-3">
        <h1 className="text-3xl md:text-5xl font-extrabold text-white">Hubungi Kami</h1>
        <p className="text-xs md:text-sm text-slate-400 max-w-md mx-auto">
          Punya pertanyaan atau ingin melakukan reservasi/pemesanan? Kirimkan pesan Anda langsung kepada kami.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="p-8 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-6">
          <h2 className="text-lg font-bold text-white">Informasi Kontak</h2>
          <div className="space-y-4 text-xs text-slate-300">
            <div className="flex items-center gap-3">
              <Phone className="h-4 w-4 text-indigo-400" />
              <span>+62 812-3456-7890</span>
            </div>
            <div className="flex items-center gap-3">
              <Mail className="h-4 w-4 text-indigo-400" />
              <span>info@${siteSlug}.com</span>
            </div>
            <div className="flex items-center gap-3">
              <MapPin className="h-4 w-4 text-indigo-400" />
              <span>Nabire, Papua Tengah, Indonesia</span>
            </div>
          </div>
        </div>

        <form className="p-8 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4">
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-300">Nama Lengkap</label>
            <input type="text" placeholder="Nama Anda" className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white" />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-300">Email</label>
            <input type="email" placeholder="email@domain.com" className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white" />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-300">Pesan / Pertanyaan</label>
            <textarea rows={4} placeholder="Tuliskan pesan Anda..." className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white" />
          </div>
          <button type="button" className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-xs transition-colors flex items-center justify-center gap-2">
            <Send className="h-3.5 w-3.5" /> Kirim Pesan
          </button>
        </form>
      </div>
    </div>
  );
}`,
  })

  // ── 9. app/loading.tsx & app/not-found.tsx ──────────────────────────────────
  files.push({
    path: "app/loading.tsx",
    content: `export default function Loading() {
  return (
    <div className="min-h-[400px] flex items-center justify-center p-12">
      <div className="h-8 w-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
    </div>
  );
}`,
  })

  files.push({
    path: "app/not-found.tsx",
    content: `import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function NotFound() {
  return (
    <div className="min-h-[400px] flex flex-col items-center justify-center p-12 text-center space-y-4">
      <h2 className="text-4xl font-extrabold text-white">404</h2>
      <p className="text-xs text-slate-400">Halaman yang Anda cari tidak ditemukan.</p>
      <Link href="/" className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-bold text-white transition-colors">
        Kembali ke Beranda
      </Link>
    </div>
  );
}`,
  })

  return files
}
