import { PrismaClient } from "@prisma/client"
import fs from "fs"
import path from "path"
import dotenv from "dotenv"

dotenv.config({ path: path.resolve(__dirname, "../../../.env") })
dotenv.config({ path: path.resolve(__dirname, "../../../.env.local") })

const prisma = new PrismaClient()

function mapType(fieldType: string): string {
  switch (fieldType) {
    case "text":
    case "richtext":
    case "string":
    case "media":
    case "date":
      return "string"
    case "number":
    case "integer":
    case "float":
    case "decimal":
      return "number"
    case "boolean":
      return "boolean"
    case "json":
      return "Record<string, unknown> | unknown[]"
    case "relation":
      // Could be expanded later to actual relation types
      return "string | Record<string, unknown>"
    default:
      return "unknown"
  }
}

async function generate() {
  console.log("Generating SDK types from database...")
  
  try {
    const contentTypes = await prisma.contentType.findMany({
      include: { fields: true },
    })
    
    const singleTypes = await prisma.singleType.findMany({
      include: { fields: true },
    })
    
    let code = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 * This file was generated by scripts/generate.ts
 */

export interface BaseEntry {
  id: string
  locale: string
  status: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED" | "REJECTED"
  publishedAt: string | null
  createdAt: string
  updatedAt: string
}
\n`

    const collectionsRecord: string[] = []
    const singlesRecord: string[] = []
    
    // Process Content Types (Collections)
    for (const ct of contentTypes) {
      const interfaceName = ct.slug.charAt(0).toUpperCase() + ct.slug.slice(1).replace(/-./g, x => x[1].toUpperCase())
      collectionsRecord.push(`    "${ct.slug}": ${interfaceName}`)
      
      code += `/** ${ct.name} (${ct.description || "No description"}) */\n`
      code += `export interface ${interfaceName} extends BaseEntry {\n`
      
      for (const field of ct.fields) {
        const type = mapType(field.type)
        const optional = !field.required ? "?" : ""
        code += `  ${field.slug}${optional}: ${type}\n`
      }
      
      code += `}\n\n`
    }
    
    // Process Single Types
    for (const st of singleTypes) {
      const interfaceName = st.slug.charAt(0).toUpperCase() + st.slug.slice(1).replace(/-./g, x => x[1].toUpperCase())
      singlesRecord.push(`    "${st.slug}": ${interfaceName}`)
      
      code += `/** ${st.name} (Single Type: ${st.description || "No description"}) */\n`
      code += `export interface ${interfaceName} extends BaseEntry {\n`
      
      for (const field of st.fields) {
        const type = mapType(field.type)
        const optional = !field.required ? "?" : ""
        code += `  ${field.slug}${optional}: ${type}\n`
      }
      
      code += `}\n\n`
    }
    
    // Registry
    code += `export interface SaCMSRegistry {\n`
    code += `  collections: {\n${collectionsRecord.join(";\n")}\n  };\n`
    code += `  singles: {\n${singlesRecord.join(";\n")}\n  };\n`
    code += `}\n`

    const outputPath = path.resolve(__dirname, "../src/generated-types.ts")
    fs.writeFileSync(outputPath, code)
    
    console.log(`✅ Successfully generated types at ${outputPath}`)
    
  } catch (error) {
    console.error("Error generating types:", error)
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

generate()
